version: '3.1'

services:
    web:
        build: 
            context: .
            dockerfile: docker/base/Dockerfile
        ports:
            - "8080:8080"
        environment:
            apicore.server.name: ApiCore
            apicore.database.host: db
            apicore.database.user: dbuser
            apicore.database.password: aaaaaa
            apicore.database.database: dbuser
        depends_on:
            - "db"
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: dbuser
            POSTGRES_PASSWORD: aaaaaa
            POSTGRES_DB: dbuser
